version: 2.1

workflows:
  test:
    jobs:
      - test

executors:
  default:
    shell: /usr/bin/env bash -euo pipefail -c
    docker:
      - image: circleci/buildpack-deps

jobs:
  test:
    executor: default
    steps:
      - checkout
      - run:
          name: diagnostics
          command: |
            set -x
            make --version || true
            git --version || true
            circleci version
            pwd || true
            tree || true
            ls -lah
            env | grep -vE '(SECRET|KEY|ACCESS|TOKEN|PASS|PWD)'
      - run:
          name: test
          command: |
            make test

